### PR TITLE
Add Victor

### PR DESCRIPTION
**Pull request by vicc30**
# Add Victor

## Changes
- Add name
- [x] Add color 

### Preview
simulator_screenshot_E8A69096-83D6-431D-85AF-AF1155CAA457

### CODE REVIEW

**Review by Gisela-Camacho-H — APPROVED** [review]

**Review by rrortegaa — APPROVED** [review]
🚀

**Review by MiguelGarciaGutierrez — APPROVED** [review]

**Review by FerUgalde253 — APPROVED** [review]
all ok

**Review by VannGarcia311 — APPROVED** [review]
Bien

**Review by danielmateos14 — APPROVED** [review]
!! Bien hecho !!

**Comment by giovanijimenez** [comment]
Bien

**Review by giovanijimenez — COMMENTED** [review]
Bien

**Pull request merged**
